### ISSUE TITLE
HTMxify Argus

### ISSUE THREAD

**Issue by hmpf** [Uninett/argus-htmx-frontend#5]
# Rationale

We have been tasked with facilitating a conversion of the GÉANT NOC's legacy dashboard GUI to Argus.  The list of requirements includes many provisions for customizing the Argus GUI outside of what is currently possible with Argus-frontend.  We only have a single React developer on our team, which turns into a bottleneck when trying to achieve velocity on feature production.

With recent projects, our team has successfully employed [HTMX](https://htmx.org/) to build new front-end applications.  We have therefore agreed to attempt writing a new web front-end for Argus, based on HTMX.  This technology is more back-end driven, and would be focused on Python, Django and good-old HTML.  These are technologies our whole team can be productive with, and where we all understand how we can make the application more customizable for users like the GÉANT NOC.

In addition to these velocity considerations, this technology stack would also make a full deployment of Argus a lot easier than it is today.  It reduces the number of steps to install, and also reduce the number of running components and domain names to maintain.

# PoC

We login with the admin login page, so no OAuth2

- [ ] Uninett/argus-htmx-frontend#1
   - [ ] Uninett/argus-htmx-frontend#2
   - [ ] Uninett/argus-htmx-frontend#3
   - [ ] Uninett/argus-htmx-frontend#4
- [x] Uninett/Argus#781
   - [ ] Uninett/Argus#788

# After PoC

- [ ] Uninett/Argus#768 
  - [ ] Polish: Include a standard theme app, overridable via setting?
- [ ] Have a local login page, does not need to use tokens
- [ ] Recreate timeslots-page with HTMx
- [ ] Recreate profiles-page with HTMx
- [ ] Recreate user-page with HTMx
